// <auto-generated />
using JewelryShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JewelryShop.Migrations
{
    [DbContext(typeof(JewerlyContext))]
    [Migration("20241204102917_a1")]
    partial class a1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JewelryShop.Models.Costumer", b =>
                {
                    b.Property<int>("CostumerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostumerID"));

                    b.Property<string>("CostumerGmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostumerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CostumerID");

                    b.ToTable("Costumers");
                });

            modelBuilder.Entity("JewelryShop.Models.Jewelry", b =>
                {
                    b.Property<int>("JewelryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JewelryID"));

                    b.Property<string>("JewelryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JewelryID");

                    b.ToTable("Jewelrys");
                });

            modelBuilder.Entity("JewelryShop.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CostumerID")
                        .HasColumnType("int");

                    b.Property<int>("JewelryID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rewiew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarAmount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CostumerID");

                    b.HasIndex("JewelryID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("JewelryShop.Models.Review", b =>
                {
                    b.HasOne("JewelryShop.Models.Costumer", "Costumer")
                        .WithMany("Reviews")
                        .HasForeignKey("CostumerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryShop.Models.Jewelry", "Jewelry")
                        .WithMany("Reviews")
                        .HasForeignKey("JewelryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Costumer");

                    b.Navigation("Jewelry");
                });

            modelBuilder.Entity("JewelryShop.Models.Costumer", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("JewelryShop.Models.Jewelry", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
